# Generated by Django 5.2.7 on 2025-11-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PENGGUNA', 'Pengguna'), ('ADMIN', 'Admin')], default='PENGGUNA', max_length=50),
        ),
    ]
