# Generated by Django 5.2.8 on 2025-11-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
